import { useCallback, useEffect, useMemo, useState } from 'react'
import { listProjectAssets } from '../../lib/api'
import { getSupabase, isSupabaseConfigured } from '../../lib/supabase/client'
import { useAuth } from '../../context/AuthContext'
import type { MediaAsset } from '../../types'

/**
 * The Deliverables stage (agency-facing): the final client-ready outputs —
 * edited videos and ad creatives/banners — produced from the Raws. These are
 * placed by Brandscape staff (uploaded "as AI") or, later, generated by the
 * banner image model. Read-only gallery with downloads.
 */
export default function DeliverablesPanel({ projectId }: { projectId: string }) {
  const { demoMode } = useAuth()
  const [assets, setAssets] = useState<MediaAsset[]>([])

  const reload = useCallback(() => {
    if (demoMode || !isSupabaseConfigured()) return
    listProjectAssets(projectId).then(setAssets).catch(() => undefined)
  }, [demoMode, projectId])

  useEffect(() => { reload() }, [reload])
  useEffect(() => {
    if (demoMode || !isSupabaseConfigured()) return
    const channel = getSupabase()
      .channel(`deliverables-${projectId}`)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'media_assets', filter: `project_id=eq.${projectId}` }, () => reload())
      .subscribe()
    return () => { getSupabase().removeChannel(channel) }
  }, [demoMode, projectId, reload])

  const deliverables = useMemo(
    () => assets.filter((a) => a.metadata?.source === 'deliverable' && a.status === 'completed'),
    [assets],
  )

  return (
    <div className="w-full">
      <p className="text-brand-500 text-xs font-body mb-4">
        Final client-ready creatives — edited videos and ad banners assembled from the Raws. Your Brandscape producer places them here as they’re finished.
      </p>

      {deliverables.length === 0 ? (
        <div className="border border-dashed border-white/10 rounded-xl px-4 py-10 text-center">
          <p className="text-brand-400 text-sm font-heading">No deliverables yet</p>
          <p className="text-brand-600 text-xs font-body mt-1">
            Once the Raws are approved, the final edited videos and ad creatives land here.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {deliverables.map((a) => (
            <div key={a.id} className="rounded-xl border border-white/10 bg-brand-900/30 overflow-hidden">
              <div className="aspect-video bg-brand-950 flex items-center justify-center">
                {a.type === 'video' ? (
                  <video src={a.url} controls className="w-full h-full object-contain" />
                ) : a.type === 'audio' ? (
                  <audio src={a.url} controls className="w-[90%]" />
                ) : (
                  <img src={a.thumbnail_url || a.url} alt={a.metadata?.name ?? 'creative'} className="w-full h-full object-contain" />
                )}
              </div>
              <div className="p-2.5 flex items-center justify-between gap-2">
                <p className="text-white text-[11px] font-heading truncate">{a.metadata?.name ?? a.type}</p>
                <a
                  href={a.url}
                  download
                  target="_blank"
                  rel="noreferrer"
                  className="shrink-0 px-2 py-1 rounded-md border border-white/15 text-brand-300 hover:text-white hover:border-white/30 text-[10px] font-heading transition-colors"
                >
                  Download
                </a>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
